### ISSUE TITLE
Illegal operation on a directory, read failed

### ISSUE THREAD

**Issue by PawelAdamski** [brunch/less-brunch#31]
After switching from brunch 2.6.0 to 2.6.5 I get following error

```
/home/pawel/Repository/........client/node_modules/brunch/lib/fs_utils/file_list.js:196
        if (error) throw new Error(formatError('Reading', error));
                   ^

Error: undefined of Error: EISDIR: illegal operation on a directory, read failed. 
  at /home/pawel/Repository/....../client/node_modules/brunch/lib/fs_utils/file_list.js:196:26
  at /home/pawel/Repository/....../client/node_modules/fcache/index.js:19:23
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:368:12)
`

I attach brunch logs and my package.json
[logs.txt](https://github.com/brunch/less-brunch/files/214681/logs.txt)
[package.json.txt](https://github.com/brunch/less-brunch/files/214684/package.json.txt)

I'm using Ubuntu 14.04

**Comment by PawelAdamski** [comment]
I have the same problem with brunch 2.7.2

**Comment by bcat-eu** [comment]
This might happen when trying to use unsafe paths, something like `import module from "module"`, replacing it with `import module from "./module"` should fix it.
